using FoodCart.Service.Models;
using System.Data.Entity;

namespace FoodCart.Service.ContextLayer
{
    /*
     * This class handles the responsibility of enabling connectivity with database 
     * 
     * It provides mapping between Customer and OnlineCustomer class with respective database entities
     * 
     * The class should ensure that seed data gets inserted at the time of instantiation
     * 
     * FluentAPI is used for ensuring values for primary key column does not get autogenerated
     * 
     */

    public class FoodContext
    {

        
    }
}
